### ISSUE TITLE
Search result / Inline related list UI

### ISSUE THREAD

**Issue by andrewbenedictwallace** [CobwebOrg/cobweb-django#72]
basically use vertical navs / tabs on the left, collapsing per-item detail on the right

**Comment by andrewbenedictwallace** [comment]
Start by refining the CollectionIndexView:
- [ ]  Use generic templates that can be reused.
- [ ]  List, not a table.
- [ ]  Record Count icons
- [ ]  Fewer (?) items per page
- [ ]  Pagination controls: use bootstrap styles
- [ ]  Set items per page
- [ ]  Click brings up collapsed detail panel

**Comment by andrewbenedictwallace** [comment]
Next reuse as much code as possible for:
- [ ] Project Index
- [ ] Resource Index
- [ ] Project Detail
- [ ] Collection Detail
- [ ] Resource Detail
